version: "3.8"

services:
  frontend-standalone:
    platform: linux/x86_64
    image: corentintrt/annexe-agency-site
    ports:
      - 3000:3000
      - 8080:8080
      - 80:80
      - 443:443
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports: 
      - 3000:3000
      - 80:80
      - 8080:8080
      - 443:443
    # volumes:
    #   - ./src:/app/src
    #   - ./styles:/app/styles
    #   - ./public:/app/public
    # env_file:
    #   - .env
